[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:$PORT --timeout 120 web_app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
